/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.recipes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Recipe service. Represents a row in the &quot;APIO_Recipe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.recipes.model.impl.RecipeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.recipes.model.impl.RecipeImpl}.
 * </p>
 *
 * @author Alejandro Hernández
 * @see Recipe
 * @see com.liferay.recipes.model.impl.RecipeImpl
 * @see com.liferay.recipes.model.impl.RecipeModelImpl
 * @generated
 */
@ProviderType
public interface RecipeModel extends BaseModel<Recipe>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recipe model instance should use the {@link Recipe} interface instead.
	 */

	/**
	 * Returns the primary key of this recipe.
	 *
	 * @return the primary key of this recipe
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recipe.
	 *
	 * @param primaryKey the primary key of this recipe
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this recipe.
	 *
	 * @return the uuid of this recipe
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this recipe.
	 *
	 * @param uuid the uuid of this recipe
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the recipe ID of this recipe.
	 *
	 * @return the recipe ID of this recipe
	 */
	public long getRecipeId();

	/**
	 * Sets the recipe ID of this recipe.
	 *
	 * @param recipeId the recipe ID of this recipe
	 */
	public void setRecipeId(long recipeId);

	/**
	 * Returns the company ID of this recipe.
	 *
	 * @return the company ID of this recipe
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this recipe.
	 *
	 * @param companyId the company ID of this recipe
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this recipe.
	 *
	 * @return the group ID of this recipe
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this recipe.
	 *
	 * @param groupId the group ID of this recipe
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this recipe.
	 *
	 * @return the user ID of this recipe
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this recipe.
	 *
	 * @param userId the user ID of this recipe
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this recipe.
	 *
	 * @return the user uuid of this recipe
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this recipe.
	 *
	 * @param userUuid the user uuid of this recipe
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this recipe.
	 *
	 * @return the user name of this recipe
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this recipe.
	 *
	 * @param userName the user name of this recipe
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this recipe.
	 *
	 * @return the create date of this recipe
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this recipe.
	 *
	 * @param createDate the create date of this recipe
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this recipe.
	 *
	 * @return the modified date of this recipe
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this recipe.
	 *
	 * @param modifiedDate the modified date of this recipe
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this recipe.
	 *
	 * @return the name of this recipe
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this recipe.
	 *
	 * @param name the name of this recipe
	 */
	public void setName(String name);

	/**
	 * Returns the region of this recipe.
	 *
	 * @return the region of this recipe
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this recipe.
	 *
	 * @param region the region of this recipe
	 */
	public void setRegion(String region);

	/**
	 * Returns the image file entry ID of this recipe.
	 *
	 * @return the image file entry ID of this recipe
	 */
	public long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this recipe.
	 *
	 * @param imageFileEntryId the image file entry ID of this recipe
	 */
	public void setImageFileEntryId(long imageFileEntryId);

	/**
	 * Returns the published date of this recipe.
	 *
	 * @return the published date of this recipe
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this recipe.
	 *
	 * @param publishedDate the published date of this recipe
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the hours to make of this recipe.
	 *
	 * @return the hours to make of this recipe
	 */
	public int getHoursToMake();

	/**
	 * Sets the hours to make of this recipe.
	 *
	 * @param hoursToMake the hours to make of this recipe
	 */
	public void setHoursToMake(int hoursToMake);

	/**
	 * Returns the minutes to make of this recipe.
	 *
	 * @return the minutes to make of this recipe
	 */
	public int getMinutesToMake();

	/**
	 * Sets the minutes to make of this recipe.
	 *
	 * @param minutesToMake the minutes to make of this recipe
	 */
	public void setMinutesToMake(int minutesToMake);

	/**
	 * Returns the steps string of this recipe.
	 *
	 * @return the steps string of this recipe
	 */
	@AutoEscape
	public String getStepsString();

	/**
	 * Sets the steps string of this recipe.
	 *
	 * @param stepsString the steps string of this recipe
	 */
	public void setStepsString(String stepsString);

	/**
	 * Returns the ingredients string of this recipe.
	 *
	 * @return the ingredients string of this recipe
	 */
	@AutoEscape
	public String getIngredientsString();

	/**
	 * Sets the ingredients string of this recipe.
	 *
	 * @param ingredientsString the ingredients string of this recipe
	 */
	public void setIngredientsString(String ingredientsString);

	/**
	 * Returns the video url of this recipe.
	 *
	 * @return the video url of this recipe
	 */
	@AutoEscape
	public String getVideoURL();

	/**
	 * Sets the video url of this recipe.
	 *
	 * @param videoURL the video url of this recipe
	 */
	public void setVideoURL(String videoURL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Recipe recipe);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Recipe> toCacheModel();

	@Override
	public Recipe toEscapedModel();

	@Override
	public Recipe toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}